# Generated by Django 3.2.7 on 2021-10-23 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20211020_1105'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
    ]
