# Generated by Django 3.2.7 on 2021-10-25 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_delete_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='PastorMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_title', models.CharField(max_length=100)),
                ('video_message', models.FileField(upload_to='video/')),
            ],
        ),
    ]
