# Generated by Django 3.2.7 on 2021-10-25 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_pastormessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pastormessage',
            name='video_message',
            field=models.URLField(),
        ),
    ]
