# Generated by Django 3.2.7 on 2021-10-25 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_pastormessage_video_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pastormessage',
            name='video_message',
            field=models.CharField(max_length=300),
        ),
    ]
