# Generated by Django 3.2.7 on 2021-10-26 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_announcement_homepageslideshow'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnouncementPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('announcementImg', models.ImageField(upload_to='')),
            ],
        ),
        migrations.DeleteModel(
            name='Announcement',
        ),
    ]
