# Generated by Django 3.2.7 on 2021-10-27 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20211026_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepageslideshow',
            name='slideshow_image1',
            field=models.ImageField(blank='True', upload_to='images'),
        ),
    ]
