# Generated by Django 3.2.7 on 2021-10-27 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_homepageslideshow_slideshow_image1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcementpage',
            name='announcementImg',
            field=models.ImageField(blank='True', upload_to='images'),
        ),
        migrations.AlterField(
            model_name='homepageslideshow',
            name='slideshow_image2',
            field=models.ImageField(blank='True', upload_to='images'),
        ),
        migrations.AlterField(
            model_name='homepageslideshow',
            name='slideshow_image3',
            field=models.ImageField(blank='True', upload_to='images'),
        ),
    ]
