# Generated by Django 3.2.7 on 2021-10-27 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20211027_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcementpage',
            name='announcementImg',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='announcementpage',
            name='body',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='homepageslideshow',
            name='slideshow_image1',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='homepageslideshow',
            name='slideshow_image2',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='homepageslideshow',
            name='slideshow_image3',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
