# Generated by Django 3.2.7 on 2021-10-28 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_auto_20211027_1319'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AnnouncementPage',
        ),
        migrations.DeleteModel(
            name='HomePageSlideshow',
        ),
    ]
