# Generated by Django 3.2.7 on 2021-10-28 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_auto_20211028_0249'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageSlideshow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slide_title', models.CharField(blank=True, max_length=250)),
                ('slideshow_image1', models.FileField(blank=True, upload_to='')),
                ('slideshow_image2', models.FileField(blank=True, upload_to='')),
                ('slideshow_image3', models.FileField(blank=True, upload_to='')),
            ],
        ),
    ]
