# Generated by Django 3.2.7 on 2021-10-28 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_announcementpage_announcement_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcementpage',
            name='announcementImg',
            field=models.FileField(blank=True, default=None, upload_to=''),
        ),
    ]
