# Generated by Django 3.2.7 on 2021-10-28 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_alter_announcementpage_announcementimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcementpage',
            name='announcementImg',
            field=models.FileField(blank=True, default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
