# Generated by Django 3.2.7 on 2021-11-08 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_alter_announcementpage_announcementimg'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistrictExecutive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('districtpastor_name', models.CharField(max_length=100, verbose_name="District Pastor's Name")),
                ('districtpastorImg', models.FileField(upload_to='')),
                ('districtsec_name', models.CharField(max_length=100, verbose_name="District Secretary's Name")),
                ('districtsecImg', models.FileField(upload_to='')),
                ('districtfin_name', models.CharField(max_length=100, verbose_name="District Financial Secretary's Name")),
                ('districtfinImg', models.FileField(upload_to='')),
                ('districtfincom_name', models.CharField(max_length=100, verbose_name="District Financial Committee Chairman's Name")),
                ('districtfincomImg', models.FileField(upload_to='')),
                ('districtmember1_name', models.CharField(max_length=100, verbose_name='District Exec Member Name')),
                ('districtmember1Img', models.FileField(upload_to='')),
                ('districtmember2_name', models.CharField(max_length=100, verbose_name='District Exec Member Name')),
                ('districtmember2Img', models.FileField(upload_to='')),
                ('districtmember3_name', models.CharField(max_length=100, verbose_name='District Exec Member Name')),
                ('districtmember3Img', models.FileField(upload_to='')),
            ],
            options={
                'verbose_name': 'District Executives',
            },
        ),
        migrations.CreateModel(
            name='NationalHead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nationalhead_name', models.CharField(max_length=100)),
                ('nationalheadImg', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='RegionalHead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regionalhead_name', models.CharField(max_length=100)),
                ('regionalheadImg', models.FileField(upload_to='')),
            ],
        ),
    ]
