# Generated by Django 3.2.7 on 2021-11-08 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_districtexecutive_nationalhead_regionalhead'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='districtexecutive',
            options={'verbose_name': 'District Executive'},
        ),
        migrations.AlterModelOptions(
            name='nationalhead',
            options={'verbose_name': 'National Head'},
        ),
    ]
