# Generated by Django 3.2.7 on 2021-11-08 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_auto_20211108_0354'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nationalhead',
            options={'verbose_name_plural': 'National Heads'},
        ),
    ]
