# Generated by Django 3.2.7 on 2021-11-08 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_alter_nationalhead_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nationalhead',
            options={'verbose_name': 'National Head', 'verbose_name_plural': 'National Heads'},
        ),
    ]
