# Generated by Django 3.2.7 on 2021-11-08 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_alter_nationalhead_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nationalhead',
            options={'verbose_name': 'National Head'},
        ),
        migrations.AlterModelOptions(
            name='regionalhead',
            options={'verbose_name': 'Regional Head'},
        ),
    ]
