# Generated by Django 3.2.7 on 2021-11-09 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_auto_20211108_0414'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChildrenMinistry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('childrenleader_name', models.CharField(max_length=100, verbose_name="District Leader's Name")),
                ('childrenleaderImg', models.FileField(upload_to='', verbose_name="District Leader's Image")),
                ('childrenslide1', models.FileField(upload_to='', verbose_name='Children Slide')),
                ('childrenslide2', models.FileField(blank=True, upload_to='', verbose_name='Children Slide')),
                ('childrenslide3', models.FileField(blank=True, upload_to='', verbose_name='Children Slide')),
            ],
            options={
                'verbose_name': 'Children Ministry',
            },
        ),
        migrations.CreateModel(
            name='EvangelismMinistry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evangelismleader_name', models.CharField(max_length=100, verbose_name="District Leader's Name")),
                ('evangelismleaderImg', models.FileField(upload_to='', verbose_name="District Leader's Image")),
                ('evangelismslide1', models.FileField(upload_to='', verbose_name='Evangelism Slide')),
                ('evangelismslide2', models.FileField(blank=True, upload_to='', verbose_name='Evangelism Slide')),
                ('evangelismslide3', models.FileField(blank=True, upload_to='', verbose_name='Evangelism Slide')),
            ],
            options={
                'verbose_name': 'Evangelism Ministry',
            },
        ),
        migrations.CreateModel(
            name='MenMinistry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menleader_name', models.CharField(max_length=100, verbose_name="District Leader's Name")),
                ('menleaderImg', models.FileField(upload_to='', verbose_name="District Leader's Image")),
                ('menslide1', models.FileField(upload_to='', verbose_name="Men's Slide")),
                ('menslide2', models.FileField(blank=True, upload_to='', verbose_name="Men's Slide")),
                ('menslide3', models.FileField(blank=True, upload_to='', verbose_name="Men's Slide")),
            ],
            options={
                'verbose_name': "Men's Ministry",
            },
        ),
        migrations.CreateModel(
            name='WomenMinistry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('womenleader_name', models.CharField(max_length=100, verbose_name="District Leader's Name")),
                ('womenleaderImg', models.FileField(upload_to='', verbose_name="District Leader's Image")),
                ('womenslide1', models.FileField(upload_to='', verbose_name="Women's Slide")),
                ('womenslide2', models.FileField(blank=True, upload_to='', verbose_name="Women's Slide")),
                ('womenslide3', models.FileField(blank=True, upload_to='', verbose_name="Women's Slide")),
            ],
            options={
                'verbose_name': "Women's Ministry",
            },
        ),
        migrations.CreateModel(
            name='YouthMinistry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('youthleader_name', models.CharField(max_length=100, verbose_name="District Leader's Name")),
                ('youthleaderImg', models.FileField(upload_to='', verbose_name="District Leader's Image")),
                ('campusslide', models.FileField(upload_to='', verbose_name='Campus Slide')),
                ('youthslide1', models.FileField(blank=True, upload_to='', verbose_name='Youth & Pensa Slide')),
                ('youthslide2', models.FileField(blank=True, upload_to='', verbose_name='Youth & Pensa Slide')),
                ('youthslide3', models.FileField(blank=True, upload_to='', verbose_name='Youth & Pensa Slide')),
            ],
            options={
                'verbose_name': 'Youth & Pensa',
            },
        ),
        migrations.AlterField(
            model_name='districtexecutive',
            name='districtfinImg',
            field=models.FileField(upload_to='', verbose_name="District Financial Secretary's Image"),
        ),
        migrations.AlterField(
            model_name='districtexecutive',
            name='districtfincomImg',
            field=models.FileField(upload_to='', verbose_name="District Financial Committee Chairman's Image"),
        ),
        migrations.AlterField(
            model_name='districtexecutive',
            name='districtmember1Img',
            field=models.FileField(upload_to='', verbose_name='District Exec Member Image'),
        ),
        migrations.AlterField(
            model_name='districtexecutive',
            name='districtmember2Img',
            field=models.FileField(upload_to='', verbose_name='District Exec Member Image'),
        ),
        migrations.AlterField(
            model_name='districtexecutive',
            name='districtmember3Img',
            field=models.FileField(upload_to='', verbose_name='District Exec Member Image'),
        ),
        migrations.AlterField(
            model_name='districtexecutive',
            name='districtpastorImg',
            field=models.FileField(upload_to='', verbose_name="District Pastor's Image"),
        ),
        migrations.AlterField(
            model_name='districtexecutive',
            name='districtsecImg',
            field=models.FileField(upload_to='', verbose_name="District Secretary's Image"),
        ),
    ]
