# Generated by Django 3.2.7 on 2021-11-09 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_auto_20211109_1217'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcementpage',
            options={'verbose_name_plural': 'Announcement Page'},
        ),
        migrations.AlterModelOptions(
            name='childrenministry',
            options={'verbose_name_plural': 'Children Ministry'},
        ),
        migrations.AlterModelOptions(
            name='districtexecutive',
            options={'verbose_name_plural': 'District Executives'},
        ),
        migrations.AlterModelOptions(
            name='evangelismministry',
            options={'verbose_name_plural': 'Evangelism Ministry'},
        ),
        migrations.AlterModelOptions(
            name='homepageslideshow',
            options={'verbose_name_plural': 'HomePage Slideshow'},
        ),
        migrations.AlterModelOptions(
            name='menministry',
            options={'verbose_name_plural': "Men's Ministry"},
        ),
        migrations.AlterModelOptions(
            name='nationalhead',
            options={'verbose_name_plural': 'National Head'},
        ),
        migrations.AlterModelOptions(
            name='pastormessage',
            options={'verbose_name_plural': 'Pastor Message'},
        ),
        migrations.AlterModelOptions(
            name='regionalhead',
            options={'verbose_name_plural': 'Regional Head'},
        ),
        migrations.AlterModelOptions(
            name='womenministry',
            options={'verbose_name_plural': "Women's Ministry"},
        ),
        migrations.AlterModelOptions(
            name='youthministry',
            options={'verbose_name_plural': 'Youth & Pensa'},
        ),
    ]
