# Generated by Django 3.2.7 on 2021-11-11 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0033_auto_20211109_1222'),
    ]

    operations = [
        migrations.CreateModel(
            name='BibleStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studyname', models.CharField(max_length=100, verbose_name='Bible Study Name')),
                ('studyurl', models.URLField(verbose_name='Book URL from AWS')),
            ],
            options={
                'verbose_name_plural': 'Bible Studies',
            },
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_title', models.CharField(max_length=100, verbose_name='Book Title')),
                ('bookurl', models.URLField(verbose_name='Book URL from ABS')),
            ],
            options={
                'verbose_name_plural': 'Inspirational Books',
            },
        ),
        migrations.CreateModel(
            name='PentecostSongs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hymnbookname', models.CharField(max_length=100, verbose_name='Hymn Book Name')),
                ('hymnbookurl', models.URLField(verbose_name='Hymn Book URL from ABS')),
            ],
            options={
                'verbose_name_plural': 'Pentecost Songs',
            },
        ),
    ]
