# Generated by Django 3.2.7 on 2021-11-11 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0034_biblestudy_books_pentecostsongs'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='biblestudy',
            options={'verbose_name_plural': 'Bible Study Manual'},
        ),
        migrations.AlterField(
            model_name='biblestudy',
            name='studyname',
            field=models.CharField(max_length=100, verbose_name='Bible Study Manual Name'),
        ),
        migrations.AlterField(
            model_name='biblestudy',
            name='studyurl',
            field=models.URLField(verbose_name='Bible Study Manual URL from AWS'),
        ),
    ]
