# Generated by Django 3.2.7 on 2021-11-11 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0035_auto_20211111_0903'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gallery_title', models.CharField(max_length=100, verbose_name='Image Title')),
                ('galleryImg', models.FileField(upload_to='', verbose_name='Image')),
            ],
            options={
                'verbose_name_plural': 'Galleries',
            },
        ),
    ]
