# Generated by Django 3.2.7 on 2021-11-14 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0036_gallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sermons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_title', models.CharField(max_length=100, verbose_name='Service Title or Date')),
                ('video_message', models.CharField(max_length=500, verbose_name='Paste Facebook or Youtube embed code here')),
            ],
            options={
                'verbose_name_plural': 'Live Service',
            },
        ),
    ]
