# Generated by Django 3.2.7 on 2021-11-22 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0037_sermons'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcementpage',
            name='body',
        ),
    ]
