# Generated by Django 3.2.7 on 2021-11-22 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0038_remove_announcementpage_body'),
    ]

    operations = [
        migrations.RenameField(
            model_name='announcementpage',
            old_name='announcementImg',
            new_name='announcementImg1',
        ),
        migrations.AddField(
            model_name='announcementpage',
            name='announcementImg2',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='announcementpage',
            name='announcementImg3',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='announcementpage',
            name='announcementImg4',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
