# Generated by Django 3.2.7 on 2021-11-22 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0039_auto_20211122_0505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcementpage',
            name='announcementImg4',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
